import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/NavBar";
import Footer from "../components/footer/Footer";
import CartDrawer from "../components/cart/CartDrawer";
import WishlistDrawer from "../components/wishlist/WishlistDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Artify India – E-Commerce for Artists",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/* Page Content */}

        <div className="relative z-10">{children}</div>
        <CartDrawer />
        <WishlistDrawer />
        <Footer />

      </body>
    </html>
  );
}
